apiVersion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  description: Ticketing Dev Env
  displayName: Ticketing Dev Env
  name: ticketing-dev
  organization: cnsc 
  tenant: cx
spec:
  description: Ticketing Dev Env
  displayName: Ticketing Dev Env
  isolationBoundary: demo
  namespaceSelector:
    names:
    - aks-westus2/ticketing-dev
  privileged: false

---
apiVersion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  description: Ticketing Prod Env
  displayName: Ticketing Prod Env
  name: ticketing-prod
  organization: cnsc 
  tenant: cx
spec:
  description: Ticketing Prod Env
  displayName: Ticketing Prod Env
  isolationBoundary: demo
  namespaceSelector:
    names:
    - eks-useast2/ticketing
    - aks-westus2/ticketing
  privileged: false

