apiVersion: rbac.tsb.tetrate.io/v2
kind: WorkspaceAccessBindings
metadata:
  name: ticketing-prod
  organization: cnsc 
  tenant: cx
  workspace: ticketing-prod
spec:
  allow:
  - role: rbac/admin
    subjects:
    - serviceAccount: admin
  - role: rbac/workspace-dev
    subjects:
    - user: organizations/cnsc/users/ffdae67c-c0b7-474d-a6fd-2acf5ecbb439

