---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: traffic-generator
  name: traffic-generator
  namespace: ticketing
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: traffic-generator
        # sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: trafficgenerator
        env:
          - name: URL
            value: "http://frontend-service/p/http/backend-service"
        args:
          - /bin/sh
          - -c
          - "while true; do curl -v -k $(URL); sleep 5; done"
        image: appropriate/curl
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 50m
            memory: 16Mi
          requests:
            cpu: 10m
            memory: 4Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
